name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 2.2.2
homepage: https://github.com/DarshanGowda0/GeoFlutterFire

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.5
  rxdart: ^0.27.3

dev_dependencies:
  flutter_lints: ^2.0.1
